name       : python-dotenv
version    : 0.19.1
release    : 3
source     :
    - https://github.com/theskumar/python-dotenv/archive/refs/tags/v0.19.1.tar.gz : 4857395ead2c459d6a8b580b0b64a4f6bcc28b09ee870fe53bcd707058e38366
license    : Apache-2.0
component  : programming.python
summary    : Python-dotenv reads key-value pairs from a .env file and can set them as environment variables.
description: |
    Python-dotenv reads key-value pairs from a .env file and can set them as environment variables.
rundeps    :
    - python3
build      : |
    %python3_setup
install    : |-
    %python3_install
